import programOne from '../assets/program-1.jpg'
import programTwo from '../assets/ .jpg'
import programThree from '../assets/program-3.jpg'
import reportImage from '../assets/report.jpg'
import webinarImage from '../assets/webinnar.png'

export const navItems = [
  ['Programs', 'programs'],
  ['Reports', 'reports'],
  ['Cyberambassador', 'fellowship'],
  ['Articles', 'articles'],
  ['Webinars', 'webinars'],
  ['Lab', 'lab'],
  ['Contribute', 'support'],
  ['Contact', 'contact'],
]

export const copy = {
  en: {
    navItems,
    title: 'SykotiCenter | Digital safety, training and advocacy in Africa',
    description:
      'SykotiCenter develops digital safety solutions, trains cyber ambassadors, publishes bimensual online threat reports, hosts webinars and advocates for better technology usage in Africa.',
    brandSubline: 'Safety, solutions, training and advocacy',
    heroEyebrow: 'African digital safety organisation',
    heroTitle: 'Safer digital lives for African communities.',
    heroText:
      'SykotiCenter builds safety tools, trains trusted ambassadors and shares practical guidance so people can use technology with confidence and purpose.',
    primaryCta: 'Explore our work',
    secondaryCta: 'Cyberambassador platform',
    reportMetric: 'public briefs and resources',
    programsKicker: 'Our programs',
    programsTitle: 'What SykotiCenter builds, teaches and shares.',
    programsText:
      'The work is organized around three visible tracks: public safety intelligence, community conversations and practical digital tools.',
    reportsKicker: 'Bimensual online threat report',
    reportsTitle: 'Read and share community safety intelligence.',
    reportsText:
      'Public briefs turn field signals into clear guidance on scams, platform risks and safer technology habits across Francophone Africa.',
    fellowshipKicker: 'Cyberambassador Fellowship',
    fellowshipTitle: 'Training certified cyber ambassadors before they use the platform.',
    fellowshipText:
      'The Fellowship prepares selected participants to educate communities, lead awareness activities and report real online safety concerns.',
    platformTitle: 'Cyberambassador Platform',
    platformText:
      'A dedicated digital environment for learning paths, resources, campaigns and ambassador community work.',
    platformCta: 'Visit dedicated page',
    webinarsKicker: 'Webinars',
    webinarsTitle: 'Focused discussions around technology usage in Francophone Africa.',
    registerInterest: 'Register interest',
    articlesKicker: 'Articles and resources',
    articlesTitle: 'Articles can cover safety, society, AI, wellbeing, policy and culture.',
    articlesText: 'This area should feel like a flexible editorial space, with image-led stories instead of plain text cards.',
    labKicker: 'Sykoti Safety Lab',
    labTitle: 'Turning field problems into simple safety products.',
    labText:
      'The Lab is not only a development team. It is where Sykoti turns recurring community problems into prototypes, workflows, toolkits and product experiments.',
    supportKicker: 'Contribute to the mission',
    supportTitle: 'Support can be money, expertise, venues, media, tools or time.',
    supportText: 'SykotiCenter can work with people and organisations through mentorship, field access, content, technical help, partnerships, sponsorship or volunteer time.',
    contactKicker: 'Work with us',
    contactTitle: 'Partner, contribute or join the SykotiCenter ecosystem.',
    contactText: 'Use the form for reports, webinars, fellowship, lab partnerships or general collaboration.',
    supportButton: 'Support the mission',
    sendButton: 'Send message',
    footer:
      'Digital solution development, community training and advocacy for safer technology usage in Africa.',
    apiFallback: 'Public API not connected yet. Showing starter content.',
    contactStatus: 'Form submitted successfully. We will contact you soon about working together.',
    supportStatus: 'Support form submitted successfully. Thank you for backing the SykotiCenter mission.',
    shareStatus: 'Report link copied for sharing.',
    shareDoneTitle: 'Report ready to share',
    shareError: 'Sharing is unavailable right now. Please try again from the report file.',
    reportOpen: 'Open',
    reportDownload: 'Download',
    reportShare: 'Share',
    reportMissing: 'This report does not have an attached file yet.',
    articlesRead: 'Read article',
    articleBack: 'Back to articles',
    articlePrevious: 'Previous articles',
    articleNext: 'Next articles',
    formSuccessTitle: 'Thank you',
    formErrorTitle: 'Action not completed',
    impactStats: [
      ['03', 'core activities'],
      ['02', 'bimensual report cycles'],
      ['01', 'first safety platform'],
      ['100%', 'community-first approach'],
    ],
    platformScreens: ['Learning path', 'Campaign kit', 'Community dashboard'],
    labItems: ['Problem discovery', 'Prototype design', 'Field testing', 'Toolkits and workflows'],
    form: {
      name: 'Name',
      namePlaceholder: 'Your name',
      orgPlaceholder: 'Your name or organisation',
      email: 'Email',
      contribution: 'Contribution type',
      contributionPlaceholder: 'Choose how you can help',
      contributionTypes: ['Mentorship or expertise', 'Venue or field access', 'Content or media relay', 'Technical/product support', 'Financial sponsorship', 'Volunteer time', 'Institutional partnership'],
      message: 'Message',
      supportPlaceholder: 'Tell us what kind of contribution you can offer.',
      contactPlaceholder: 'Tell us what you want to build, report or organize.',
      topic: 'Topic',
      topicPlaceholder: 'Choose a topic',
      topics: ['Cyberambassador Fellowship', 'Online threat report', 'Webinar', 'Sykoti Safety Lab', 'Partnership'],
    },
    programs: [
      {
        id: 'reports',
        label: 'Threat intelligence',
        title: 'Bimensual Online Threat Report',
        description:
          'Readable briefs on phishing, fake investments, unsafe apps, misinformation and digital wellbeing risks.',
        image: reportImage,
        actions: ['Read briefs', 'Share insights', 'Track patterns'],
      },
      {
        id: 'webinars',
        label: 'Discussion spaces',
        title: 'Online Webinars on Tech Usage',
        description:
          'Open sessions where youth, parents, builders, educators and partners discuss how technology is used and misused.',
        image: programTwo,
        actions: ['Join sessions', 'Suggest topics', 'Invite speakers'],
      },
      {
        id: 'lab',
        label: 'Digital solutions',
        title: 'Sykoti Safety Lab',
        description:
          'Research, design and product work for tools that help people stay safer online.',
        image: reportImage,
        actions: ['Prototype tools', 'Test with users', 'Build partnerships'],
      },
    ],
    starterReports: [
      {
        title: 'Threat Watch: Mobile Money & WhatsApp Impersonation',
        theme: 'Observed scams, warning signs and family-safe prevention actions.',
        date: 'Bimensual report',
        source: 'SykotiCenter Watch Desk',
        fileName: 'Public brief',
        image: reportImage,
      },
      {
        title: 'Digital Wellbeing Signals for Youth Communities',
        theme: 'Gaming, betting, AI content, privacy and attention risks.',
        date: 'Community insight',
        source: 'Cyberambassador Fellowship',
        fileName: 'Field notes',
        image: reportImage,
      },
    ],
    webinars: [
      { title: 'AI, trust and daily tech usage in Francophone Africa', date: 'Next live', audience: 'Youth, creators, educators', image: webinarImage },
      { title: 'Online scams: what communities are really seeing', date: 'Roundtable', audience: 'Parents, NGOs, local leaders', image: webinarImage },
      { title: 'Building useful safety tools with African users', date: 'Lab session', audience: 'Developers, designers, partners', image: webinarImage },
    ],
    articles: [
      { title: 'Digital safety basics for families', slug: 'digital-safety-basics-for-families', excerpt: 'A starter resource for safer conversations at home.', content: 'Digital safety starts with simple family routines: keep devices updated, protect accounts with strong passwords, discuss suspicious links before anyone clicks, and agree on what information should stay private. These small habits make it easier for children, parents and caregivers to pause, verify and ask for help when something online feels wrong.', category: 'Guide', author: 'SykotiCenter', image: programOne },
      { title: 'How to recognize online manipulation', slug: 'how-to-recognize-online-manipulation', excerpt: 'Signals communities can use before they click, pay or share.', content: 'Online manipulation often creates urgency, fear or excitement so people react quickly. Before sharing money, documents or personal details, check the sender, compare the claim with a trusted source, and ask whether the message is pushing you to act without thinking. Community awareness grows when people share warning signs early.', category: 'Awareness', author: 'SykotiCenter', image: programTwo },
      { title: 'AI, attention and young people online', slug: 'ai-attention-and-young-people-online', excerpt: 'A wider editorial angle on habits, wellbeing and digital culture.', content: 'AI tools can help young people learn, create and solve problems, but they also reshape attention, trust and identity. Safer use means teaching verification, protecting personal data, keeping human judgment in important decisions, and designing online routines that leave room for rest, school and community life.', category: 'Culture', author: 'SykotiCenter', image: programThree },
    ],
  },
  fr: {
    navItems: [
      ['Programmes', 'programs'],
      ['Rapports', 'reports'],
      ['Cyberambassador', 'fellowship'],
      ['Articles', 'articles'],
      ['Webinaires', 'webinars'],
      ['Lab', 'lab'],
      ['Contribuer', 'support'],
      ['Contact', 'contact'],
    ],
    title: 'SykotiCenter | Sécurité numérique, formation et plaidoyer en Afrique',
    description:
      'SykotiCenter développe des solutions de sécurité numérique, forme des cyberambassadeurs, publie des rapports bimensuels, anime des webinaires et plaide pour un meilleur usage de la technologie en Afrique.',
    brandSubline: 'Sécurité, solutions, formation et plaidoyer',
    heroEyebrow: 'Organisation africaine de sécurité numérique',
    heroTitle: 'Des vies numériques plus sûres pour les communautés africaines.',
    heroText:
      'SykotiCenter crée des outils, forme des ambassadeurs de confiance et partage des ressources pratiques pour utiliser la technologie avec assurance et intention.',
    primaryCta: 'Explorer nos actions',
    secondaryCta: 'Plateforme Cyberambassador',
    reportMetric: 'briefs publics et ressources',
    programsKicker: 'Nos programmes',
    programsTitle: 'Ce que SykotiCenter construit, enseigne et partage.',
    programsText:
      'Le travail s’organise autour de trois axes visibles : veille utile, conversations communautaires et outils numériques pratiques.',
    reportsKicker: 'Rapport bimensuel sur les menaces en ligne',
    reportsTitle: 'Lire et partager une veille utile pour les communautés.',
    reportsText:
      'Les briefs publics transforment les signaux terrain en conseils clairs sur les arnaques, les risques de plateforme et les bons usages numériques.',
    fellowshipKicker: 'Fellowship Cyberambassador',
    fellowshipTitle: 'Former des cyberambassadeurs certifiés avant l’usage de la plateforme.',
    fellowshipText:
      'Le Fellowship prépare des participants sélectionnés à sensibiliser les communautés, animer des actions et remonter les préoccupations cyber réelles.',
    platformTitle: 'Plateforme Cyberambassador',
    platformText:
      'Un espace numérique dédié aux parcours d’apprentissage, aux ressources, aux campagnes et au travail communautaire des ambassadeurs.',
    platformCta: 'Visiter la page dédiée',
    webinarsKicker: 'Webinaires',
    webinarsTitle: 'Des discussions ciblées sur les usages technologiques en Afrique francophone.',
    registerInterest: 'Manifester son intérêt',
    articlesKicker: 'Articles et ressources',
    articlesTitle: 'Les articles peuvent parler sécurité, société, IA, bien-être, politique et culture.',
    articlesText: 'Cette partie doit rester un espace éditorial flexible, avec des contenus visuels plutôt que de simples cartes texte.',
    labKicker: 'Sykoti Safety Lab',
    labTitle: 'Transformer les problèmes terrain en produits simples.',
    labText:
      'Le Lab n’est pas seulement une équipe de développement. C’est l’endroit où Sykoti transforme des problèmes récurrents en prototypes, workflows, toolkits et expérimentations produit.',
    supportKicker: 'Contribuer à la mission',
    supportTitle: 'Le soutien peut être financier, technique, humain, média ou terrain.',
    supportText: 'SykotiCenter peut collaborer via du mentorat, des lieux, du relais média, de l’expertise technique, des partenariats, du sponsoring ou du volontariat.',
    contactKicker: 'Travailler avec nous',
    contactTitle: 'Devenir partenaire, contribuer ou rejoindre l’écosystème SykotiCenter.',
    contactText: 'Utilisez le formulaire pour les rapports, webinaires, fellowship, partenariats lab ou collaborations.',
    supportButton: 'Soutenir la mission',
    sendButton: 'Envoyer le message',
    footer:
      'Développement de solutions, formation communautaire et plaidoyer pour un usage plus sûr de la technologie en Afrique.',
    apiFallback: 'API publique non connectée. Affichage du contenu de démarrage.',
    contactStatus: 'Formulaire bien soumis. Nous vous contacterons bientôt pour travailler ensemble.',
    supportStatus: 'Formulaire de soutien bien soumis. Merci de contribuer à la mission SykotiCenter.',
    shareStatus: 'Lien du rapport copié pour le partage.',
    shareDoneTitle: 'Rapport prêt à partager',
    shareError: 'Le partage est indisponible pour le moment. Réessayez depuis le fichier du rapport.',
    reportOpen: 'Ouvrir',
    reportDownload: 'Télécharger',
    reportShare: 'Partager',
    reportMissing: 'Ce rapport n’a pas encore de fichier associé.',
    articlesRead: 'Lire l’article',
    articleBack: 'Retour aux articles',
    articlePrevious: 'Articles précédents',
    articleNext: 'Articles suivants',
    formSuccessTitle: 'Merci',
    formErrorTitle: 'Action non terminée',
    impactStats: [
      ['03', 'activités principales'],
      ['02', 'cycles de veille bimensuels'],
      ['01', 'première plateforme de sécurité'],
      ['100%', 'approche communautaire'],
    ],
    platformScreens: ['Parcours de formation', 'Kit campagne', 'Tableau communautaire'],
    labItems: ['Identifier le problème', 'Designer un prototype', 'Tester sur le terrain', 'Créer toolkits et workflows'],
    form: {
      name: 'Nom',
      namePlaceholder: 'Votre nom',
      orgPlaceholder: 'Votre nom ou organisation',
      email: 'Email',
      contribution: 'Type de contribution',
      contributionPlaceholder: 'Choisir comment vous pouvez aider',
      contributionTypes: ['Mentorat ou expertise', 'Lieu ou accès terrain', 'Contenu ou relais média', 'Support technique/produit', 'Sponsoring financier', 'Temps volontaire', 'Partenariat institutionnel'],
      message: 'Message',
      supportPlaceholder: 'Dites-nous quel type de contribution vous pouvez proposer.',
      contactPlaceholder: 'Dites-nous ce que vous voulez construire, signaler ou organiser.',
      topic: 'Sujet',
      topicPlaceholder: 'Choisir un sujet',
      topics: ['Fellowship Cyberambassador', 'Rapport sur les menaces en ligne', 'Webinaire', 'Sykoti Safety Lab', 'Partenariat'],
    },
    programs: [
      {
        id: 'reports',
        label: 'Veille cyber utile',
        title: 'Rapport bimensuel sur les menaces',
        description:
          'Briefs lisibles sur phishing, faux investissements, applications à risque, désinformation et bien-être numérique.',
        image: reportImage,
        actions: ['Lire les briefs', 'Partager les signaux', 'Suivre les tendances'],
      },
      {
        id: 'webinars',
        label: 'Espaces de discussion',
        title: 'Webinaires sur les usages technologiques',
        description:
          'Sessions ouvertes avec jeunes, parents, builders, éducateurs et partenaires sur les usages et abus de la technologie.',
        image: programTwo,
        actions: ['Rejoindre', 'Proposer un sujet', 'Inviter des experts'],
      },
      {
        id: 'lab',
        label: 'Solutions numériques',
        title: 'Sykoti Safety Lab',
        description:
          'Recherche, design et produit pour des outils qui aident les personnes à rester plus en sécurité en ligne.',
        image: reportImage,
        actions: ['Prototyper', 'Tester terrain', 'Créer des partenariats'],
      },
    ],
    starterReports: [
      {
        title: 'Veille menace : mobile money et usurpation WhatsApp',
        theme: 'Arnaques observées, signaux d’alerte et gestes de prévention familiaux.',
        date: 'Rapport bimensuel',
        source: 'SykotiCenter Watch Desk',
        fileName: 'Brief public',
        image: reportImage,
      },
      {
        title: 'Signaux de bien-être numérique chez les jeunes',
        theme: 'Jeux, paris, contenus IA, vie privée et risques d’attention.',
        date: 'Retour terrain',
        source: 'Fellowship Cyberambassador',
        fileName: 'Notes terrain',
        image: reportImage,
      },
    ],
    webinars: [
      { title: 'IA, confiance et usages quotidiens en Afrique francophone', date: 'Prochain live', audience: 'Jeunes, créateurs, éducateurs', image: webinarImage },
      { title: 'Arnaques en ligne : ce que voient les communautés', date: 'Table ronde', audience: 'Parents, ONG, leaders locaux', image: webinarImage },
      { title: 'Construire des outils de sécurité avec les utilisateurs africains', date: 'Session lab', audience: 'Développeurs, designers, partenaires', image: webinarImage },
    ],
    articles: [
      { title: 'Bases de sécurité numérique pour les familles', slug: 'bases-de-securite-numerique-pour-les-familles', excerpt: 'Une ressource de départ pour des conversations plus sûres à la maison.', content: 'La sécurité numérique commence avec des habitudes simples en famille : mettre les appareils à jour, protéger les comptes avec des mots de passe solides, discuter des liens suspects avant de cliquer et définir les informations qui doivent rester privées. Ces gestes aident chacun à vérifier, demander conseil et réagir calmement face aux risques en ligne.', category: 'Guide', author: 'SykotiCenter', image: programOne },
      { title: 'Reconnaître la manipulation en ligne', slug: 'reconnaitre-la-manipulation-en-ligne', excerpt: 'Des signaux à vérifier avant de cliquer, payer ou partager.', content: 'La manipulation en ligne crée souvent de l’urgence, de la peur ou de l’excitation pour pousser à réagir vite. Avant de partager de l’argent, des documents ou des données personnelles, vérifiez l’expéditeur, comparez l’information avec une source fiable et demandez-vous si le message vous empêche de réfléchir. Une communauté plus sûre partage les signaux d’alerte tôt.', category: 'Awareness', author: 'SykotiCenter', image: programTwo },
      { title: 'IA, attention et jeunesse connectée', slug: 'ia-attention-et-jeunesse-connectee', excerpt: 'Un angle éditorial plus large sur les usages, le bien-être et la culture numérique.', content: 'Les outils IA peuvent aider les jeunes à apprendre, créer et résoudre des problèmes, mais ils influencent aussi l’attention, la confiance et l’identité. Un usage plus sûr passe par la vérification, la protection des données personnelles, le jugement humain dans les décisions importantes et des routines numériques qui laissent de la place au repos, à l’école et à la vie communautaire.', category: 'Culture', author: 'SykotiCenter', image: programThree },
    ],
  },
}
