const guardianVoiceCopy = {
  en: {
    '.back-link': 'Back to website <span aria-hidden="true">↗</span>', '.intro .eyebrow': '30-day digital awareness campaign',
    '.intro h1': 'Guardians Voice Challenge <em>— Application Form</em>',
    '.intro>p': 'Your voice can make the digital space safer. Join the Guardians Voice Challenge, get trained, create impactful content, and spend 30 days raising awareness about online safety and responsible digital citizenship.',
    '.intro-facts': '<span><strong>30 days</strong>of consistent action</span><span><strong>Training</strong>and campaign resources</span><span><strong>Your voice</strong>for safer digital spaces</span>',
    '#aboutHeading': 'About you', '[aria-labelledby="aboutHeading"] .section-heading p': 'Tell us how to reach you.',
    '#presenceHeading': 'Your digital presence', '[aria-labelledby="presenceHeading"] .section-heading p': 'A quick picture of how you currently use digital platforms.',
    '#whyHeading': 'Why Guardians Voice?', '[aria-labelledby="whyHeading"] .section-heading p': 'Help us understand what you care about.',
    '#commitmentHeading': 'Your commitment', '[aria-labelledby="commitmentHeading"] .section-heading p': 'Be honest about what you can sustain for 30 days.',
    '#challengeHeading': 'Final challenge question', '[aria-labelledby="challengeHeading"] .section-heading p': 'Give us a glimpse of your voice.', '#confirmationHeading': 'Confirmation',
    '.commitment-note strong': '30 days. One shared mission.', '.commitment-note p': 'The Guardians Voice Challenge runs for 30 days. Participants will receive training and campaign resources and will be expected to regularly create and publish awareness content, including short videos, throughout the campaign.',
    '.submit-note': 'Fields marked * are required. Your application is securely sent to Sykoti Center.', 'footer span': 'Safer digital lives for African communities.',
  },
  fr: {
    '.back-link': 'Retour au site web <span aria-hidden="true">↗</span>', '.intro .eyebrow': 'Campagne de sensibilisation numérique de 30 jours',
    '.intro h1': 'Challenge Guardians Voice <em>— Formulaire de candidature</em>',
    '.intro>p': 'Votre voix peut rendre l’espace numérique plus sûr. Rejoignez le Challenge Guardians Voice, suivez une formation, créez des contenus percutants et consacrez 30 jours à la sensibilisation à la sécurité en ligne et à la citoyenneté numérique responsable.',
    '.intro-facts': '<span><strong>30 jours</strong>d’engagement régulier</span><span><strong>Formation</strong>et ressources de campagne</span><span><strong>Votre voix</strong>pour des espaces numériques plus sûrs</span>',
    '#aboutHeading': 'À propos de vous', '[aria-labelledby="aboutHeading"] .section-heading p': 'Indiquez-nous comment vous joindre.',
    '#presenceHeading': 'Votre présence numérique', '[aria-labelledby="presenceHeading"] .section-heading p': 'Un aperçu des plateformes numériques que vous utilisez actuellement.',
    '#whyHeading': 'Pourquoi Guardians Voice ?', '[aria-labelledby="whyHeading"] .section-heading p': 'Aidez-nous à comprendre ce qui vous tient à cœur.',
    '#commitmentHeading': 'Votre engagement', '[aria-labelledby="commitmentHeading"] .section-heading p': 'Indiquez honnêtement ce que vous pouvez maintenir pendant 30 jours.',
    '#challengeHeading': 'Question finale du challenge', '[aria-labelledby="challengeHeading"] .section-heading p': 'Donnez-nous un aperçu de votre voix.', '#confirmationHeading': 'Confirmation',
    '.commitment-note strong': '30 jours. Une mission commune.', '.commitment-note p': 'Le Challenge Guardians Voice dure 30 jours. Les participants recevront une formation et des ressources de campagne. Ils devront créer et publier régulièrement des contenus de sensibilisation, notamment de courtes vidéos, tout au long de la campagne.',
    '.submit-note': 'Les champs marqués d’un * sont obligatoires. Votre candidature est envoyée en toute sécurité à Sykoti Center.', 'footer span': 'Des vies numériques plus sûres pour les communautés africaines.',
  },
}
const guardianVoiceFields = {
  fullName:['Full name','Nom complet'],email:['Email address','Adresse e-mail'],whatsapp:['WhatsApp number with country code','Numéro WhatsApp avec indicatif du pays'],age:['Age','Âge'],gender:['Gender','Genre'],country:['Country','Pays'],city:['City','Ville'],occupation:['Current occupation/status','Occupation/statut actuel'],otherOccupation:['Please specify','Veuillez préciser'],socialProfiles:['Social media profile links','Liens vers vos profils sur les réseaux sociaux'],contentExample:['If yes, share one example or link','Si oui, partagez un exemple ou un lien'],motivation:['Why do you want to become a <strong>Guardians Voice Challenger</strong>?','Pourquoi souhaitez-vous devenir <strong>Challenger Guardians Voice</strong> ?'],digitalIssue:['Which digital issue would you most like to raise awareness about?','Quel enjeu numérique aimeriez-vous le plus faire connaître ?'],otherDigitalIssue:['Please specify the issue','Veuillez préciser l’enjeu'],dailyTime:['How much time can you realistically dedicate to the challenge each day?','Combien de temps pouvez-vous consacrer de manière réaliste au challenge chaque jour ?'],challengeAnswer:['Imagine you have <strong>30 seconds</strong> to convince another young person to take their online safety seriously. What would you tell them?','Imaginez que vous avez <strong>30 secondes</strong> pour convaincre un autre jeune de prendre sa sécurité en ligne au sérieux. Que lui diriez-vous ?']
}
const guardianVoiceLegends = {
  platforms:['Which platforms do you currently use?','Quelles plateformes utilisez-vous actuellement ?'],hasCreatedContent:['Have you ever created videos or digital content?','Avez-vous déjà créé des vidéos ou du contenu numérique ?'],trainingCommitment:['Are you willing to participate in the initial training?','Acceptez-vous de participer à la formation initiale ?'],publishingCommitment:['Are you willing to create and publish content throughout the 30-day challenge?','Acceptez-vous de créer et publier du contenu pendant les 30 jours du challenge ?'],hasEquipmentAccess:['Do you have access to a smartphone and internet connection for content creation?','Avez-vous accès à un smartphone et à une connexion Internet pour créer du contenu ?']
}
const guardianVoiceOptions = {
  occupation:[['Select one','Student','Professional','Entrepreneur','Content Creator','Other'],['Sélectionnez une réponse','Étudiant(e)','Professionnel(le)','Entrepreneur(e)','Créateur·rice de contenu','Autre']],
  digitalIssue:[['Select one','Online safety','Cyberbullying','Scams & fraud','Privacy & personal data','Misinformation','Responsible social media use','AI & emerging technologies','Other'],['Sélectionnez une réponse','Sécurité en ligne','Cyberharcèlement','Arnaques et fraudes','Vie privée et données personnelles','Désinformation','Usage responsable des réseaux sociaux','IA et technologies émergentes','Autre']],
  dailyTime:[['Select one','Less than 30 minutes','30–60 minutes','1–2 hours','More than 2 hours'],['Sélectionnez une réponse','Moins de 30 minutes','30 à 60 minutes','1 à 2 heures','Plus de 2 heures']]
}
function setGuardianVoiceLanguage(language) {
  const fr=language==='fr', index=fr?1:0
  document.documentElement.lang=language
  document.title=fr?'Challenge Guardians Voice — Formulaire de candidature | Sykoti Center':'Guardians Voice Challenge — Application Form | Sykoti Center'
  document.querySelector('.brand').setAttribute('aria-label',fr?'Accueil de Sykoti Center':'Sykoti Center home')
  document.querySelector('.language-toggle').setAttribute('aria-label',fr?'Choisir la langue':'Choose language')
  document.querySelectorAll('[data-language]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.language===language)))
  Object.entries(guardianVoiceCopy[language]).forEach(([selector,html])=>{const el=document.querySelector(selector);if(el)el.innerHTML=html})
  Object.entries(guardianVoiceFields).forEach(([id,copies])=>{const label=document.querySelector(`label[for="${id}"]`);if(label)label.innerHTML=`${copies[index]}${['gender','socialProfiles','contentExample'].includes(id)?` <small>${fr?'(facultatif)':'(optional)'}</small>`:['motivation','challengeAnswer'].includes(id)?'':' <b>*</b>'}`})
  const hints={whatsapp:['Begin with + and your country code.','Commencez par + suivi de l’indicatif de votre pays.'],socialProfiles:['One complete link per line.','Un lien complet par ligne.']}
  Object.entries(hints).forEach(([id,copies])=>{const el=document.querySelector(`#${id}`).closest('.field').querySelector(':scope > small');if(el)el.textContent=copies[index]})
  Object.entries(guardianVoiceLegends).forEach(([name,copies])=>{const legend=name==='platforms'?document.querySelector('.form-section fieldset legend'):document.querySelector(`input[name="${name}"]`).closest('fieldset').querySelector('legend');legend.innerHTML=`${copies[index]}${name==='platforms'?'':' <b>*</b>'}`})
  Object.entries(guardianVoiceOptions).forEach(([id,copies])=>document.querySelectorAll(`#${id} option`).forEach((option,i)=>{if(copies[index][i])option.textContent=copies[index][i]}))
  document.querySelectorAll('.choice input').forEach(input=>{const node=[...input.closest('label').childNodes].find(n=>n.nodeType===Node.TEXT_NODE&&n.textContent.trim());if(!node)return;if(input.value==='yes')node.textContent=fr?'Oui':'Yes';else if(input.value==='no')node.textContent=fr?'Non':'No';else if(input.value==='Other')node.textContent=fr?'Autre':'Other'})
  const confirmations=fr?['Je comprends que le dépôt d’une candidature ne garantit pas la sélection et que les Challengers sélectionnés devront participer activement tout au long de la campagne.','Je comprends que <strong>des récompenses spéciales sont prévues pour les participants qui terminent avec succès le Challenge Guardians Voice</strong>, conformément aux critères d’achèvement du challenge.']:['I understand that applying does not automatically guarantee selection and that selected Challengers are expected to actively participate throughout the campaign.','I understand that <strong>special rewards are available to participants who successfully complete the Guardians Voice Challenge</strong>, according to the challenge completion criteria.']
  document.querySelectorAll('.confirm-choice span').forEach((el,i)=>el.innerHTML=confirmations[i])
  const button=document.querySelector('#submitButton');if(!button.disabled)button.innerHTML=`${fr?'DEVENIR CHALLENGER GUARDIANS VOICE':'APPLY TO BECOME A GUARDIAN VOICE'} <span aria-hidden="true">→</span>`
  document.querySelectorAll('[data-max-words]').forEach(field=>{const count=field.value.trim().split(/\s+/).filter(Boolean).length;document.querySelector(`[data-count-for="${field.id}"]`).textContent=`${count} / ${field.id==='motivation'?150:100} ${fr?'mots':'words'}`})
  localStorage.setItem('guardiansVoiceLanguage',language)
}
window.guardianVoiceErrorMessage=message=>{
  if(document.documentElement.lang!=='fr')return message
  const known={
    'Please review the highlighted fields before submitting your application.':'Veuillez vérifier les champs signalés avant d’envoyer votre candidature.','Enter complete profile links beginning with https://, one per line.':'Saisissez des liens complets commençant par https://, un par ligne.','Please write at least 5 words.':'Veuillez rédiger au moins 5 mots.','Please write at least 3 words.':'Veuillez rédiger au moins 3 mots.','Please use no more than 150 words.':'Veuillez ne pas dépasser 150 mots.','Please use no more than 100 words.':'Veuillez ne pas dépasser 100 mots.','The application service is unavailable right now. Please check your connection and try again.':'Le service de candidature est momentanément indisponible. Vérifiez votre connexion et réessayez.','Your application could not be submitted. Please try again.':'Votre candidature n’a pas pu être envoyée. Veuillez réessayer.',
    'Please enter your full name.':'Veuillez saisir votre nom complet.','Please enter a valid email address.':'Veuillez saisir une adresse e-mail valide.','Enter your WhatsApp number with its country code, beginning with +.':'Saisissez votre numéro WhatsApp avec l’indicatif du pays, en commençant par +.','Please enter a valid age.':'Veuillez saisir un âge valide.','Country and city are required.':'Le pays et la ville sont obligatoires.','Please select your current occupation or status.':'Veuillez sélectionner votre occupation ou statut actuel.','Please specify your current occupation or status.':'Veuillez préciser votre occupation ou statut actuel.','One or more selected platforms are invalid.':'Une ou plusieurs plateformes sélectionnées ne sont pas valides.','Social profile links must be valid web addresses, one per line.':'Les liens de profils doivent être des adresses web valides, un par ligne.','Please tell us whether you have created digital content before.':'Veuillez indiquer si vous avez déjà créé du contenu numérique.','The content example must be a valid web address.':'L’exemple de contenu doit être une adresse web valide.','Your motivation must be between 5 and 150 words.':'Votre motivation doit compter entre 5 et 150 mots.','Please select a digital issue.':'Veuillez sélectionner un enjeu numérique.','Please specify the digital issue you want to address.':'Veuillez préciser l’enjeu numérique que vous souhaitez aborder.','Please answer all three challenge commitment questions.':'Veuillez répondre aux trois questions sur votre engagement.','Please select the time you can dedicate each day.':'Veuillez sélectionner le temps que vous pouvez consacrer chaque jour.','Your 30-second answer must be between 3 and 100 words.':'Votre réponse de 30 secondes doit compter entre 3 et 100 mots.','Please accept both confirmation statements.':'Veuillez accepter les deux déclarations de confirmation.','An application has already been submitted with this email address.':'Une candidature a déjà été envoyée avec cette adresse e-mail.','Too many attempts. Please wait a few minutes and try again.':'Trop de tentatives. Veuillez patienter quelques minutes avant de réessayer.'
  };return known[message]||message
}
document.querySelectorAll('[data-language]').forEach(button=>button.addEventListener('click',()=>setGuardianVoiceLanguage(button.dataset.language)))
setGuardianVoiceLanguage(localStorage.getItem('guardiansVoiceLanguage')==='fr'?'fr':'en')
